### ISSUE TITLE
rspamd pod keeps restarting

### ISSUE THREAD

**Issue by bramhoven** [bramhoven/wildduck-k8s#16]
No reason found yet

**Comment by marxlnfcs** [comment]
Hello!
I found a solution for this "bug".

If you're looking into the /var/log/rspamd/rspamd.log file you can see rspamd has to generate some TLDs but this takes way too long. So I updated the resource limits:

```
resources:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
```

Now its working :)
